apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: app
    repoURL: https://github.com/nguyencuong30697/Crawler-app-argoCD
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true

# - - -
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: db
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: db
    repoURL: https://github.com/nguyencuong30697/Crawler-app-argoCD
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true

